# Generated by Django 4.2.2 on 2023-06-26 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="category", name="category_number",),
        migrations.AlterField(
            model_name="inventory",
            name="count",
            field=models.IntegerField(blank=True, null=True, verbose_name="수량(갯수)"),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="weight",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="무게(g)"
            ),
        ),
    ]
