# Generated by Django 4.0.3 on 2023-05-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('business_number', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('seller_email', models.EmailField(max_length=45)),
                ('seller_name', models.CharField(max_length=20)),
                ('seller_birthday', models.CharField(max_length=20)),
                ('seller_address', models.CharField(max_length=40)),
                ('seller_phone', models.CharField(max_length=15)),
                ('seller_password', models.CharField(max_length=30)),
            ],
        ),
    ]
