# Generated by Django 4.2.2 on 2023-06-13 11:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("seller", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Business",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("business_number", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Ceo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ceo_email", models.EmailField(max_length=45)),
                ("ceo_name", models.CharField(max_length=20)),
                ("ceo_birthday", models.CharField(max_length=20)),
                ("ceo_address", models.CharField(max_length=40)),
                ("ceo_phone", models.CharField(max_length=15)),
                ("ceo_password", models.CharField(max_length=30)),
                ("ceo_password2", models.CharField(max_length=30)),
                (
                    "ceo_business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="seller.business",
                    ),
                ),
            ],
        ),
    ]
