# Generated by Django 4.2.2 on 2023-06-15 05:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("seller", "0002_business_ceo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="business_number",
            field=models.CharField(max_length=20, verbose_name="사업자번호"),
        ),
        migrations.CreateModel(
            name="Market",
            fields=[
                (
                    "marketkey",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("market_number", models.CharField(max_length=15)),
                ("market_address", models.CharField(max_length=70)),
                ("market_type", models.CharField(max_length=20)),
                ("market_content", models.CharField(max_length=500)),
                (
                    "market_ceo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="seller.ceo"
                    ),
                ),
            ],
        ),
    ]
