# Generated by Django 4.2.2 on 2023-06-19 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("seller", "0003_alter_business_business_number_market"),
    ]

    operations = [
        migrations.RenameField(
            model_name="business", old_name="business_number", new_name="business",
        ),
    ]
